name: FutureApp
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com
# author: hacksy <email@example.com>

environment:
  sdk: '>=2.0.0 <3.0.0'
  http: 0.12.0+1
#dependencies:
#  path: ^1.4.1

dev_dependencies:
  test: ^1.0.0
